export interface Language {
  code: string;
  name: string;
  nativeName: string;
}

export const LANGUAGE_KEY = 'ai_chatbot_language';

export const languages: Language[] = [
  { code: 'tr', name: 'Türkçe', nativeName: 'Türkçe' },
  { code: 'en', name: 'İngilizce', nativeName: 'English' },
  { code: 'de', name: 'Almanca', nativeName: 'Deutsch' },
  { code: 'fr', name: 'Fransızca', nativeName: 'Français' },
  { code: 'es', name: 'İspanyolca', nativeName: 'Español' },
  { code: 'it', name: 'İtalyanca', nativeName: 'Italiano' },
  { code: 'pt', name: 'Portekizce', nativeName: 'Português' },
  { code: 'ru', name: 'Rusça', nativeName: 'Русский' },
  { code: 'ar', name: 'Arapça', nativeName: 'العربية' },
  { code: 'zh', name: 'Çince (Basitleştirilmiş)', nativeName: '中文(简体)' },
  { code: 'zh-TW', name: 'Çince (Geleneksel)', nativeName: '中文(繁體)' },
  { code: 'ja', name: 'Japonca', nativeName: '日本語' },
  { code: 'ko', name: 'Korece', nativeName: '한국어' },
  { code: 'hi', name: 'Hintçe', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengalce', nativeName: 'বাংলা' },
  { code: 'nl', name: 'Felemenkçe', nativeName: 'Nederlands' },
  { code: 'pl', name: 'Lehçe', nativeName: 'Polski' },
  { code: 'uk', name: 'Ukraynaca', nativeName: 'Українська' },
  { code: 'cs', name: 'Çekçe', nativeName: 'Čeština' },
  { code: 'sv', name: 'İsveççe', nativeName: 'Svenska' },
  { code: 'da', name: 'Danca', nativeName: 'Dansk' },
  { code: 'fi', name: 'Fince', nativeName: 'Suomi' },
  { code: 'no', name: 'Norveççe', nativeName: 'Norsk' },
  { code: 'el', name: 'Yunanca', nativeName: 'Ελληνικά' },
  { code: 'hu', name: 'Macarca', nativeName: 'Magyar' },
  { code: 'ro', name: 'Romence', nativeName: 'Română' },
  { code: 'bg', name: 'Bulgarca', nativeName: 'Български' },
  { code: 'hr', name: 'Hırvatça', nativeName: 'Hrvatski' },
  { code: 'sk', name: 'Slovakça', nativeName: 'Slovenčina' },
  { code: 'sl', name: 'Slovence', nativeName: 'Slovenščina' },
  { code: 'sr', name: 'Sırpça', nativeName: 'Српски' },
  { code: 'lt', name: 'Litvanca', nativeName: 'Lietuvių' },
  { code: 'lv', name: 'Letonca', nativeName: 'Latviešu' },
  { code: 'et', name: 'Estonca', nativeName: 'Eesti' },
  { code: 'th', name: 'Tayca', nativeName: 'ไทย' },
  { code: 'vi', name: 'Vietnamca', nativeName: 'Tiếng Việt' },
  { code: 'id', name: 'Endonezce', nativeName: 'Bahasa Indonesia' },
  { code: 'ms', name: 'Malayca', nativeName: 'Bahasa Melayu' },
  { code: 'tl', name: 'Filipince', nativeName: 'Filipino' },
  { code: 'sw', name: 'Svahili', nativeName: 'Kiswahili' },
  { code: 'af', name: 'Afrikaanca', nativeName: 'Afrikaans' },
  { code: 'he', name: 'İbranice', nativeName: 'עברית' },
  { code: 'fa', name: 'Farsça', nativeName: 'فارسی' },
  { code: 'ur', name: 'Urduca', nativeName: 'اردو' },
  { code: 'ta', name: 'Tamilce', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Teluguca', nativeName: 'తెలుగు' },
  { code: 'ml', name: 'Malayalamca', nativeName: 'മലയാളം' },
  { code: 'kn', name: 'Kannadaca', nativeName: 'ಕನ್ನಡ' },
  { code: 'gu', name: 'Güceratça', nativeName: 'ગુજરાતી' },
  { code: 'mr', name: 'Marathice', nativeName: 'मराठी' },
  { code: 'pa', name: 'Pencapça', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'ne', name: 'Nepalce', nativeName: 'नेपाली' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල' },
  { code: 'my', name: 'Birmanca', nativeName: 'မြန်မာ' },
  { code: 'km', name: 'Kmerce', nativeName: 'ខ្មែរ' },
  { code: 'lo', name: 'Laoça', nativeName: 'ລາວ' },
  { code: 'ka', name: 'Gürcüce', nativeName: 'ქართული' },
  { code: 'hy', name: 'Ermenice', nativeName: 'Հայերեն' },
  { code: 'az', name: 'Azerice', nativeName: 'Azərbaycan' },
  { code: 'uz', name: 'Özbekçe', nativeName: 'Oʻzbekcha' },
  { code: 'kk', name: 'Kazakça', nativeName: 'Қазақша' },
  { code: 'mn', name: 'Moğolca', nativeName: 'Монгол' },
  { code: 'sq', name: 'Arnavutça', nativeName: 'Shqip' },
  { code: 'mk', name: 'Makedonca', nativeName: 'Македонски' },
  { code: 'bs', name: 'Boşnakça', nativeName: 'Bosanski' },
  { code: 'is', name: 'İzlandaca', nativeName: 'Íslenska' },
  { code: 'ga', name: 'İrlandaca', nativeName: 'Gaeilge' },
  { code: 'cy', name: 'Galce', nativeName: 'Cymraeg' },
  { code: 'mt', name: 'Maltaca', nativeName: 'Malti' },
  { code: 'eu', name: 'Baskça', nativeName: 'Euskara' },
  { code: 'ca', name: 'Katalanca', nativeName: 'Català' },
  { code: 'gl', name: 'Galiçyaca', nativeName: 'Galego' },
  { code: 'la', name: 'Latince', nativeName: 'Latina' },
  { code: 'eo', name: 'Esperanto', nativeName: 'Esperanto' },
  { code: 'haw', name: 'Hawaiice', nativeName: 'ʻŌlelo Hawaiʻi' },
  { code: 'mi', name: 'Maori', nativeName: 'Te Reo Māori' },
  { code: 'am', name: 'Amharca', nativeName: 'አማርኛ' },
  { code: 'zu', name: 'Zuluca', nativeName: 'isiZulu' },
  { code: 'xh', name: 'Zosaca', nativeName: 'isiXhosa' },
  { code: 'yo', name: 'Yorubaca', nativeName: 'Yorùbá' },
  { code: 'ig', name: 'İgboca', nativeName: 'Igbo' },
  { code: 'ha', name: 'Hausaca', nativeName: 'Hausa' },
  { code: 'so', name: 'Somalice', nativeName: 'Soomaali' },
  { code: 'mg', name: 'Malgaşça', nativeName: 'Malagasy' },
  { code: 'ku', name: 'Kürtçe', nativeName: 'Kurdî' },
  { code: 'ps', name: 'Peştuca', nativeName: 'پښتو' },
  { code: 'sd', name: 'Sintçe', nativeName: 'سنڌي' },
  { code: 'ky', name: 'Kırgızca', nativeName: 'Кыргызча' },
  { code: 'tg', name: 'Tacikçe', nativeName: 'Тоҷикӣ' },
  { code: 'tk', name: 'Türkmence', nativeName: 'Türkmen' },
  { code: 'tt', name: 'Tatarca', nativeName: 'Татарча' },
  { code: 'co', name: 'Korsikaca', nativeName: 'Corsu' },
  { code: 'fy', name: 'Frizce', nativeName: 'Frysk' },
  { code: 'gd', name: 'İskoç Galcesi', nativeName: 'Gàidhlig' },
  { code: 'lb', name: 'Lüksemburgca', nativeName: 'Lëtzebuergesch' },
  { code: 'sm', name: 'Samoaca', nativeName: 'Gagana Samoa' },
  { code: 'sn', name: 'Şonaca', nativeName: 'chiShona' },
  { code: 'st', name: 'Sotoca', nativeName: 'Sesotho' },
  { code: 'su', name: 'Sundaca', nativeName: 'Basa Sunda' },
  { code: 'jw', name: 'Cavaca', nativeName: 'Basa Jawa' },
  { code: 'ceb', name: 'Sebuanosça', nativeName: 'Cebuano' },
  { code: 'hmn', name: 'Hmongca', nativeName: 'Hmoob' },
  { code: 'ny', name: 'Çiçevaca', nativeName: 'Chichewa' },
  { code: 'yi', name: 'Yidişçe', nativeName: 'ייִדיש' },
];

export const getLanguageByCode = (code: string): Language => {
  return languages.find(l => l.code === code) || languages[0];
};
