// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { Session, SupabaseClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

let client: SupabaseClient<Database> | null = null;

try {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error('Supabase URL or publishable key is missing');
  }

  const parsedUrl = new URL(SUPABASE_URL);
  if (!['http:', 'https:'].includes(parsedUrl.protocol)) {
    throw new Error('Supabase URL is invalid');
  }

  client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
} catch (error) {
  console.warn('[Supabase] Unavailable, running in demo mode.', error);
}

export const supabase = client as SupabaseClient<Database>;
export const isSupabaseConfigured = client !== null;

let initialSessionPromise: Promise<Session | null> | undefined;

export const getInitialSession = () => {
  if (!isSupabaseConfigured) return Promise.resolve(null);
  initialSessionPromise ??= Promise.race([
    supabase.auth.getSession().then(({ data }) => data.session),
    new Promise<Session | null>((_, reject) => {
      setTimeout(() => reject(new Error('Supabase session timed out')), 2500);
    }),
  ]);
  return initialSessionPromise;
};